services:
  app-pipeline:
    image: python:3.10-slim
    container_name: python-pipeline
    depends_on:
      - mongo-server
    volumes:
      - .:/app
    working_dir: /app
    # En tu docker-compose.yml
    command: sh -c "pip install -r requirements.txt && python scripts/ingesta.py && python scripts/limpieza.py && python scripts/carga_bd.py"
    networks:
      - mongodb_network

  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-server:27017/
    ports:
      - "8081:8081"
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network: